// <auto-generated />
using System;
using Agentor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agentor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgentorDbContext))]
    partial class AgentorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.AgentRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("agent_name");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<DateTimeOffset?>("ReviewRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_requested_at");

                    b.Property<string>("ReviewWorkflowStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("review_workflow_status");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminal_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("HumanReviewDecisionsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("human_review_decisions_json");

                    b.Property<Guid?>("KnowledgeScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_scope_id");

                    b.Property<string>("SessionMemoryJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_memory_json");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("objective");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ResumeCursorJson")
                        .HasColumnType("text")
                        .HasColumnName("resume_cursor_json");

                    b.Property<long>("AggregateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.ToTable("agent_runs", (string)null);
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.AgentStepRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("agent_steps", (string)null);
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.PolicyDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.ToTable("policy_decisions", (string)null);
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.ToolCallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_json");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("output_json");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.Property<string>("ToolKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tool_key");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.ToTable("tool_calls", (string)null);
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.TraceEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_json");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kind");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("trace_events", (string)null);
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.AgentRunIdempotencyRecord", b =>
                {
                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_fingerprint");

                    b.HasKey("IdempotencyKey");

                    b.ToTable("agent_run_idempotency_keys", (string)null);
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.OutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.RunQueueItemRecord", b =>
                {
                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("agent_name");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("claimed_by");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("EnqueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at_utc");

                    b.Property<string>("ExecutionMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("execution_mode");

                    b.Property<Guid?>("KnowledgeScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_scope_id");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("objective");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("SkillKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("skill_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToolInputJson")
                        .HasColumnType("text")
                        .HasColumnName("tool_input_json");

                    b.Property<string>("ToolPayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("tool_payload_json");

                    b.Property<string>("ToolKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tool_key");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("WorkItemId");

                    b.HasIndex("Status", "EnqueuedAtUtc");

                    b.ToTable("run_queue_items", (string)null);
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.ExecutionLeaseRecord", b =>
                {
                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("LeaseHolder")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("lease_holder");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.HasKey("ResourceId");

                    b.ToTable("execution_leases", (string)null);
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.DistributedOperationRecord", b =>
                {
                    b.Property<DateTimeOffset>("CommittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at_utc");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("operation_key");

                    b.HasKey("OperationKey");

                    b.ToTable("distributed_operations", (string)null);
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.AgentStepRecord", b =>
                {
                    b.HasOne("Agentor.Infrastructure.Persistence.Records.AgentRunRecord", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.PolicyDecisionRecord", b =>
                {
                    b.HasOne("Agentor.Infrastructure.Persistence.Records.AgentStepRecord", "Step")
                        .WithMany("PolicyDecisions")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.ToolCallRecord", b =>
                {
                    b.HasOne("Agentor.Infrastructure.Persistence.Records.AgentStepRecord", "Step")
                        .WithMany("ToolCalls")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.TraceEventRecord", b =>
                {
                    b.HasOne("Agentor.Infrastructure.Persistence.Records.AgentRunRecord", "Run")
                        .WithMany("TraceEvents")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.AgentRunRecord", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("TraceEvents");
                });

            modelBuilder.Entity("Agentor.Infrastructure.Persistence.Records.AgentStepRecord", b =>
                {
                    b.Navigation("PolicyDecisions");

                    b.Navigation("ToolCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
